### PR TITLE
Add Audiofab pith + chorus/flanging patches

### PR DESCRIPTION
**Pull request by markmelvin**
Sync fork with upstream master.
Add new Audiofab patch bank for pitch shift plus chorus and flanging.

### CODE REVIEW

**Comment by mstratman** [comment]
This is great, thanks. Was this comment intended to be multi-line? Or do you mind if I put it on a single line?

**Comment by markmelvin** [comment]
> This is great, thanks. Was this comment intended to be multi-line? Or do you mind if I put it on a single line?

Hey Mark! I assumed it had to be broken up. It can be a single line if it wraps automatically.  The other entries of ours can be fixed too, I guess.  But we may be releasing some reverb patches too later this week - should we wait and put them both in the same PR?

**Comment by mstratman** [comment]
Ok thanks, I switched it to a single line. Not a huge deal, but I have a handful of tools in various languages that all share this file, so it's just to prevent problems from bad JSON parsers.

**Comment by markmelvin** [comment]
Awesome - thanks, Mark.

**Comment by markmelvin** [comment]
I don't see the new one on https://mstratman.github.io/fv1-programs/ . Was I supposed to regenerate or do something else? I forget...

**Comment by mstratman** [comment]
Sorry about that; it's fixed now.  Yes I forgot to generate it. It's still a manual process  (`yarn generate` then `git rm <deleted>` `git add <new>`)

**Comment by markmelvin** [comment]
Ah, great! Thanks again!

**Pull request merged**
